import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Link01Page: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/">
          <a id="go-to-homepage">
            <h1 className={styles.title}>Homepage</h1>
          </a>
        </Link>

        <div className={styles.grid}>
          <h2 id="title">Link 02</h2>
        </div>
      </main>
    </div>
  );
};

export default Link01Page;
